branches:
  only:
    - master
    - dev

version: '0.1.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64\\Scripts\\activate.bat"
      PYTHON_VERSION: 3.7
    - PYTHON: "C:\\Miniconda3-x64\\Scripts\\activate.bat"
      PYTHON_VERSION: 3.8


platform:
  - x64

configuration:
  - Release

install:
  - cmd: set PATH="C:\\Miniconda3-x64\\Scripts\\";"C:\\Miniconda3-x64\\";%PATH%
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -n base conda=4.8.2
  - cmd: conda install conda-build anaconda-client
  - cmd: conda config --set ssl_verify false
  - cmd: conda env create -f environment.yml -n test_env python=$PYTHON_VERSION
  - cmd: activate test_env
  - cmd: conda install pytest-cov
  # https://pythonhosted.org/CodeChat/appveyor.yml.html
  - cmd: python -m pip install -U pip
  - cmd: python -m easy_install -U setuptools

build_script:
  - cmd: python setup.py install

test_script:
  - cmd: pytest libpyhat/

on_success:
  - cmd: activate base
  # - cmd: conda config --set anaconda_upload yes
  # - cmd: conda build -c conda-forge -c usgs-astrogeology --token %CONDA_UPLOAD_TOKEN% RECIPEPATH .
  # - cmd: set builddir = conda build recipe --output;
  - ps:
      echo $env:APPVEYOR_PULL_REQUEST_NUMBER;
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
            echo "Uploading Package";
            conda config --set anaconda_upload yes;
            conda build --token %CONDA_UPLOAD_TOKEN% --python %PYTHON_VERSION% -c usgs-astrogeology recipe;
          };
      };
