branches:
  only:
    - master
    - dev

version: '0.1.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64\\Scripts\\activate.bat"
      PYTHON_VERSION: 3.7
    - PYTHON: "C:\\Miniconda3-x64\\Scripts\\activate.bat"
      PYTHON_VERSION: 3.8


platform:
  - x64

configuration:
  - Release

install:
  - cmd: set PATH="C:\\Miniconda3-x64\\Scripts\\";"C:\\Miniconda3-x64\\";%PATH%
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda config --set ssl_verify false
  - cmd: conda env create -f environment.yml -n test_env python=$env:PYTHON_VERSION
  - cmd: call conda activate test_env
  - cmd: conda install pytest-cov
  # https://pythonhosted.org/CodeChat/appveyor.yml.html
  - cmd: python -m pip install -U pip
  - cmd: python -m easy_install -U setuptools

build_script:
  - cmd: python setup.py install

test_script:
  - cmd: pytest libpyhat/

on_success:
  # - cmd: coveralls
  - cmd: activate base
  # - cmd: conda config --set anaconda_upload yes
  # - cmd: conda build -c conda-forge -c usgs-astrogeology --token %CONDA_UPLOAD_TOKEN% RECIPEPATH .
  # - cmd: set builddir = conda build recipe --output;

deploy_script:
  ps: deployment/deploy.ps1 $env:PYTHON_VERSION
