name: pyhat
channels:
  - conda-forge
  - usgs-astrogeology
dependencies:
  - python>=3
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - multipledispatch
  - yaml
  - pvl
  - plio
  - matplotlib
  - pywavelets
